# This file stores your secrets.
# Do not share it or commit it to version control.

JOTFORM_API_KEY = "22179825a79dba61013e4fc3b9d30fa4"
JOTFORM_FORM_ID = "252598168633065"

[users]
Megan = { name = "Megan", password = "pioneer123", role = "admin" }
Karter = { name = "Karter", password = "pioneer123", role = "user" }
BJ = { name = "Bj", password = "pioneer123", role = "admin" }
Gillian = { name = "Gillian", password = "pioneer123", role = "user" }
Gabby = { name = "Gabby", password = "pioneer123", role = "user" }
Billy = { name = "Billy", password = "pioneer123", role = "user" }
